services:
  app:
    image: ghcr.io/v4nixd/requiem-discord:latest
    container_name: requiem_discord
    network_mode: host
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./config.yaml:/app/config.yaml:ro
